name: Deploy Static Web App to Azure

on:
  push:
    branches:
      - main # Deploys when changes are pushed to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Explicitly use Node.js 20

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: '/' # The directory containing your static files (index.html)
          output_location: '/' # The directory where your files will be served from
