name: Deploy Static Web App to Azure

on:
  push:
    branches:
      - main # The branch  index.html is located

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: '/' # Directory containing source file (index.html)
          output_location: '/' # Directory where built files will be served from
