name: Deploy to Azure Static Web App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Azure Static Web App
      uses: azure/static-web-apps-deploy@v1
      with:
        azureStaticWebAppsApiToken: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}  
        name: Index-Page  
        appLocation: ./ 
        outputLocation: ./dist 

