name: Deploy to Azure Static Web App

env:
  APP_LOCATION: "/" # location of your client code
  OUTPUT_LOCATION: "build" # location of client code build output

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
          submodules: true

    - name: Deploy to Azure Static Web App
      uses: azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}  
        action: "upload"
        app_Location: ./ 
        output_Location: ./dist 

